name: macos

on: [pull_request]

jobs:
  build:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - run: |
          cd src/macos/ATDriverGenericMacOS
          xcodebuild
      - run: |
          pluginkit -e use -i com.bocoup.ATDriverGenericMacOS.ATDriverGenericMacOSExtension
          defaults write com.apple.Accessibility SpeechVoiceIdentifierForLanguage '{2 = {en = "com.bocoup.ATDriverGenericMacOS.ATDriverGenericMacOSExtension.ATDriverGenericMacOSExtension";};}'
          say hello
          log show --process ATDriverGenericService | tail -n 10
