name: Node.js CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-2022]
        node-version: ['18.x']
        test-command:
          - npm run test-style
          - npm run test-types
          - npm run test-unit

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: ${{ matrix.test-command }}
